### ISSUE TITLE
Open HTML tag at start of a long file causes parser to take forever

### ISSUE THREAD

**Issue by cesquivias** [greghendershott/markdown#49]
I wrote a [long blog post](https://github.com/cesquivias/cesquivias.github.io/blob/master/_src/posts/2014-12-15-writing-a-language-in-truffle-part-2.md) using Frog and left an unclosed HTML tag towards the front of the file (`<TODO>`). When trying to convert the file to HTML the parser hung. It sent my CPU to 100% and didn't finish after 5 min. The memory usage was oscillating around 200MB so it appears to be doing a lot of backtracking.

This sounds related to issue #43 but wanted to provide an test case I came across.

**Comment by greghendershott** [comment]
Although this is still a worst-case corner of the grammar, the worst case should be significantly faster as a result of #51.  As a result I'm going to close this. However if you think the performance is still not good enough, please feel free to comment here and I'll re-open it.
