### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by cwebber** [greghendershott/markdown#53]
Unlicensed software is nonfree software... could we get a COPYING? :)

**Comment by amirouche** [comment]
+1

**Comment by greghendershott** [comment]
The [LICENSE file is down in the `markdown` collection directory](https://github.com/greghendershott/markdown/blob/master/markdown/LICENSE). This means it is copied by `raco pkg install`.

**Comment by greghendershott** [comment]
Having said that, it looks like the copyright date needs updating in the LICENSE file of a few of my Racket packages.

**Comment by cwebber** [comment]
@greghendershott Ah okay, thanks!  I guess I'm not used to it being in that location... toplevel is usually where I look.  (Maybe a relative symlink would help people like me find it?)

**Comment by greghendershott** [comment]
@cwebber I know what you mean. In fact in some older repos, that predate Racket's new package manager, I do have it at the top.

I seem to recall reading that sym links and git don't play well? But I don't know.

I could at least link to the LICENSE in the README.md.

**Comment by tfeb** [comment]
@greghendershott: git is fine with symlinks: GitHub might not be but that seems unlikely.

**Comment by cwebber** [comment]
git is indeed fine with symlinks, and iirc so is github.

**Comment by greghendershott** [comment]
Thanks, that's good to know. But how about Windows? Example of what I'd read: [Git Symlinks in Windows](http://stackoverflow.com/questions/5917249/git-symlinks-in-windows).

Although I rarely use Windows these days except to test things, I try to support it. At least not knowingly de-support it. :) For example Frog is supposed to work for Windows users; it depends on this markdown parser package.

Would one of you like to make the change, test this on Windows and submit a pull request? :)

**Comment by tfeb** [comment]
I don't have access to Windows any more, but it sounds like a good reason to avoid symlinks!
