### ISSUE TITLE
Parsing of not-quite-malformed Markdown takes a long time

### ISSUE THREAD

**Issue by nxg** [greghendershott/markdown#54]
When the markdown parser parses the text below, it takes a _long_ time to do it:

    % time .../m2h try-md.md 
    Doing try-md.md
    '#(#<void>)
    .../m2h try-md.md  6.68s user 0.17s system 100% cpu 6.836 total
    %

(the `m2h` script does little more than parse the markdown and then dump it to HTML).

Now, the text here is obviously not very good markdown – it's just a list of filenames – but it _is_ just text, and I would have expected the parser to broadly cope with it, even if the result isn't pretty.  The case this is a reduction of consisted of about double this number of lines, and I thought the parser had crashed.  Is there perhaps something _O(n^2)_ happening here?

Now, one response to ‘the parser is slow when I give it rubbish markdown’ is ‘well, don't do that, then’.  That is perfectly fair.  But if there's some way of getting the parser to give up gracefully, that would be nice.

----

    font-util-1.3.0_1   Create an index of X font files in a directory
    fontconfig-2.11.0_1,1 XML-based font configuration API for X Windows
    fontsproto-2.1.2    Fonts extension headers
    freetype2-2.5.2     Free and portable TrueType font rendering engine
    gdk-pixbuf2-2.28.2  Graphic library for GTK+
    gettext-0.18.3.1    GNU gettext package
    git-1.8.5.2         Distributed source code management tool
    glib-2.36.3_1       Some useful routines of C programming (current stable versi
    gmake-3.82_1        GNU version of 'make' utility
    gnome_subr-1.0      Common startup and shutdown subroutines used by GNOME scrip
    gnomehier-3.0       A utility port that creates the GNOME directory tree
    gobject-introspection-1.36.0_2 Generate interface introspection data for GObject libraries
    graphite2-1.2.4     Rendering capabilities for complex non-Roman writing system
    gtk-update-icon-cache-2.24.22 Gtk-update-icon-cache utility from the Gtk+ toolkit
    gtk3-3.8.8          Gimp Toolkit for X11 GUI (current stable version)
    harfbuzz-0.9.25     OpenType text shaping engine
    hicolor-icon-theme-0.12 A high-color icon theme shell from the FreeDesktop project
    icu-50.1.2          International Components for Unicode (from IBM)
    inputproto-2.3      Input extension headers
    intltool-0.50.2     Tools to internationalize various kinds of data files
    jasper-1.900.1_12   An implementation of the codec specified in the JPEG-2000 s
    jbigkit-1.6         Lossless compression for bi-level images such as scanned pa
    jpeg-8_4            IJG's jpeg compression utilities
    kbproto-1.0.6       KB extension headers
    lcms2-2.5           Accurate, fast, and small-footprint color management engine
    libICE-1.0.8,1      Inter Client Exchange library for X11
    libSM-1.2.2,1       Session Management library for X11
    libX11-1.6.2,1      X11 library
    libXau-1.0.8        Authentication Protocol library for X11
    libXcomposite-0.4.4,1 X Composite extension library
    libXcursor-1.1.14   X client-side cursor loading library
    libXdamage-1.1.4    X Damage extension library
    libXdmcp-1.1.1      X Display Manager Control Protocol library
    libXext-1.3.2,1     X11 Extension library
    libXfixes-5.0.1     X Fixes extension library
    libXfont-1.4.7,1    X font library
    libXft-2.3.1        Client-sided font API for X applications
    libXi-1.7.2,1       X Input extension library
    libXinerama-1.1.3,1 X11 Xinerama library
    libXrandr-1.4.2     X Resize and Rotate extension library
    libXrender-0.9.8    X Render extension library
    libXt-1.1.4,1       X Toolkit library
    libXtst-1.2.2       X Test extension
    libcheck-0.9.11     Unit test framework for C
    libgcrypt-1.5.3     General purpose crypto library based on code used in GnuPG
    libgpg-error-1.12   Common error values for all GnuPG components
    libiconv-1.14_1     A character set conversion library
    libpthread-stubs-0.3_4 This library provides weak aliases for pthread functions
    libtool-2.4.2_2     Generic shared library support script
    libxcb-1.9.3        The X protocol C-language Binding (XCB) library
    libxml2-2.8.0_3     XML parser library for GNOME
    libxslt-1.1.28_1    The XSLT C library for GNOME

**Comment by greghendershott** [comment]
An interesting thing about this example is the underline `_` characters.

If I replace those with say  `-` or `\_`, the time falls from ~4000 ms to ~16 ms.

The markdown parser is supposed to parse pairs of `_` as italic (`<em>`), and it is supposed handle nested pairs across multiple source lines:

```
(parse-markdown "_a _b_\n c_")
'((p () (em () "a " (em () "b") "  c")))
```

It knows that italics won't extend beyond paragraph boundaries. But it sees this mass of text as one long-ish paragraph. In your example it is often searching to the end of the paragraph.

Maybe I can optimize that. (Also I should double-check that it ought to handle _nested_ underline and bolds.)

But even with that, I think you'd get a result you still don't want, just get it faster. ;)  You don't want `<em>`, you want those treated as literal `_`s, I think?

I don't see any obvious way for it to understand these are supposed to be literal `_`s. I think you will need to give it a hint by one of:

- escaping each `_` as `\_`
- enclosing each filename in code spans with backticks e.g. `` `lib-foo-1.1.1_1` ``
- enclosing the whole text in a code block with triple backticks:
   
            ```
            font-util-1.3.0_1   Create an index of X font files in a directory
            fontconfig-2.11.0_1,1 XML-based font configuration API for X Windows
            fontsproto-2.1.2    Fonts extension headers
            and so on
            ```

Depending on which is the least inconvenient with your input, and the closest to how you want the output to appear?

**Comment by nxg** [comment]
Thanks for your thoughts. I think in this case I'd simply want the wrong result faster!

In this particular case, I'm bulk-converting fairly scrappy how-to text notes.  Some of these are quite carefully written as Markdown (and more will be like this once I start routinely converting these in this way), some have a few random Markdown features in an otherwise unformatted file (because I automatically put `quotes round code` these days), and some are just a blob of text with chunks such as this cut-and-pasted in place.  So the formatted result of this case is clearly a mess, and I understand why when I look at the resulting HTML, but I probably won't bother fixing it until I want to re-read those notes some time.

So I don't think it's useful for the parser to knock itself out trying to make sense of rather garbled content like this; failing fast might be more valuable, and letting the user realise their error or decide not to fix it.  An ideal behaviour, I think, would be for the parser to simply give up in disgust at some point: 'this is a mess; I'm not going to waste cycles on you any more...' *parser stalks off in a huff, slamming the lid behind it...*

**Comment by greghendershott** [comment]
I'll look at this. Meanwhile if "wrong, faster" might suit your specific application, here's an idea (please hold your nose):

```
(require racket/sandbox)
(define (parse-markdown-half-heartedly text [seconds 1.0])
  ;; If text doesn't parse as markdown within seconds, return a list
  ;; of xexprs consisting of a single code element wrapping the
  ;; original text as-is.
  (with-handlers ([exn:fail:resource? (λ _ `((code () ,text)))])
    (with-limits seconds #f (parse-markdown text))))
```

I realize if `text` is an entire file, this might be "too wrong, fast".

**Comment by nxg** [comment]
Ooooh, I like it (damn: now I feel dirty...)

**Comment by greghendershott** [comment]
Actually I see something I can improve. It should fail when a potentially opening `_` immediately follows an alphanumeric character. It already fails when a potentially closing `_` immediately precedes an alphanumeric character. So it already ignores e.g. `snake_case_var`. But it fails on the `_var` not earlier on the `snake_`. In your example, that makes a big difference.

I tweaked the grammar. It passes the full test suite. But I'm mulling it over before I commit and push.

**Comment by greghendershott** [comment]
I will push my grammar fix. It makes your example parse very quickly, < 20 ms.


Maybe you do still want the time-limit hack for belt+suspenders against potential similar slow parses.

BTW in that hack, substitute `pre` for `code`. I already fixed the comment, above. I don't recall if GitHub will email you because I edited the comment.
