### ISSUE TITLE
observe `xexpr-drop-empty-attributes`?

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/markdown#61]
The [`xexpr-drop-empty-attributes`](http://docs.racket-lang.org/xml/index.html?q=xexpr-drop-empty-attributes#%28def._%28%28lib._xml%2Fmain..rkt%29._xexpr-drop-empty-attributes%29%29) parameter in `xml/xexpr` controls whether empty attribute lists are omitted from X-expressions. 

`parse-markdown` makes X-expressions, but does not observe this parameter. Can it? Should it?

```racket
(parameterize ([xexpr-drop-empty-attributes #t])
  (parse-markdown "I am _emph_ and I am **strong**."))

> '((p () "I am " (em () "emph") " and I am " (strong () "strong") "."))

;; vs. '((p "I am " (em "emph") " and I am " (strong "strong") "."))
```

**Comment by mbutterick** [comment]
(PS Obviously stripping the attributes afterwards is simple. This issue should not be mistaken for anything serious.)

**Comment by greghendershott** [comment]
It's a good question. I have mixed feelings about xexpr attributes being optional. That's convenient when typing xexprs by hand. OTOH when consuming xexprs, it's more convenient if they're always normalized to include an attribute list. A client of this package doesn't need to handle them being optional. So I think the status quo is a plus?

**Comment by mbutterick** [comment]
Fair enough. For Pollen I considered both options. I ended up going the opposite way (= no empty attr lists) because most tags don't have attributes, and the annoyance (to humans) of the extra housekeeping seemed to outweigh the benefits (to machines) of having them. Still, truly minor.
