### ISSUE TITLE
`parse-markdown` does not detect a list item without a blank line before

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/markdown#62]
I believe these should parse out the same way, but they do not.

```racket
#lang at-exp racket
(require markdown)

(parse-markdown @string-append{Line
* List item.})

(parse-markdown @string-append{Line
                               
* List item.})
```

**Comment by greghendershott** [comment]
It's more common for them to differ, according to this [useful yet horrifying site](http://johnmacfarlane.net/babelmark2/?normalize=1&text=Line%0A*+bullet%3F%0A%0ALine%0A%0A*+bullet%3F).

**Comment by mbutterick** [comment]
Gott im Himmel
