### ISSUE TITLE
When parsing markdown from a string, carriage returns mess up newline parsing

### ISSUE THREAD

**Issue by lexi-lambda** [greghendershott/markdown#63]
Carriage returns in strings break the markdown parser’s newline handling:

```racket
> (parse-markdown "hello\n\nworld!")
'((p () "hello") (p () "world!"))
> (parse-markdown "hello\r\n\r\nworld!")
'((p () "hello\r \r world!"))
```

This appears to be because carriage returns are only stripped when reading from a file path, [as is currently implemented on lines 102-104 of parse.rkt](https://github.com/greghendershott/markdown/blob/55b3ac2ec038ce5af92d770ec3a7ddec2bef49dd/markdown/parse.rkt#L102-L104). The same logic to strip carriage returns probably also needs to be applied when the input is a bare string.

**Comment by greghendershott** [comment]
Thank you for reporting this. I pushed a fix.
