### ISSUE TITLE
Images not produced correctly

### ISSUE THREAD

**Issue by hjek** [greghendershott/markdown#77]
In plain Markdown `![foo](bar)` produces the image `bar` with the alternate text `foo`:

```
echo '![foo](bar)'|markdown
<p><img src="bar" alt="foo" /></p>
```

This Markdown parser wraps the image in a `div` tag with the `figure` class and a `foo` caption:

```
> (parse-markdown "![foo](bar)")
'((div
   ((class "figure"))
   (img ((src "bar") (alt "foo")))
   (p ((class "caption")) "foo")))
```

**Comment by greghendershott** [comment]
Keep in mind that (similar to pandoc) this library has a `current-strict-markdown?` parameter.

When `current-strict-markdown?` is `#t`, it does produce:

```
'((p () (img ((src "bar") (alt "foo")))))`.
```

It sounds like you want to use that?

---

When `current-strict-markdown?` is `#f`, it produces (as you said):

```racket
'((div
   ((class "figure"))
   (img ((src "bar") (alt "foo")))
   (p ((class "caption")) "foo")))
```

From [looking at this in Babelmark](https://johnmacfarlane.net/babelmark2/?normalize=1&text=!%5Bfoo%5D(bar)) I think the latter could be updated to use HTML5 elements:

```racket
`((figure
   (img ((src "bar") (alt "foo")))
   (figcaption "foo")))
```

Doing so would break users of this, until they make a (simple I think?) update to their CSS.

Although I'm not eager to add tons of parameters, maybe there should be a new `use-html5?` parameters to control stuff like this. But probably I won't do anything unless/until anyone says they really do need/want this.

**Comment by greghendershott** [comment]
p.s. Even with `current-strict-markdown?` set to `#t`, you may find this library produces something that doesn't fit "the" markdown "specification". The [Babelmark FAQ](https://johnmacfarlane.net/babelmark2/faq.html) is worth reading. The short version is, the Babelmark site wouldn't exist if there actually were a markdown specification. :smile:

**Comment by hjek** [comment]
> Even with current-strict-markdown? set to #t, you may find this library produces something that doesn't fit "the" markdown "specification".

Thanks! Yes, I realize that Gruber's "spec" is ambiguous at best, but with `current-strict-markdown?` your parser behaves a bit more like Github Markdown.

Well, at least some people have [written a proper spec](https://spec.commonmark.org/current/), even if actual implementations diverge wildly.
