### ISSUE TITLE
quotation mode causes centering, not blockquote

### ISSUE THREAD

**Issue by shriram** [greghendershott/markdown#85]
`>` in Markdown is supposed to produce a blockquote, per Gruber's original spec, so (e.g.) a indented nesting in Scribble.

However, it seems to produce centered text. The input file [loading context given in https://github.com/greghendershott/markdown/issues/84]

![image](https://user-images.githubusercontent.com/75030/92530229-fe128a00-f1f9-11ea-82b2-9bedefa9d867.png)

results in

![image](https://user-images.githubusercontent.com/75030/92530267-0ff42d00-f1fa-11ea-9058-d9a0a807f59f.png)

**Comment by greghendershott** [comment]
For context see #84.

It's changing `<blockquote>` to Scribble `centered` because it was the least-worst thing I could think to do.

What Scribble form would you recommend to use instead of `centered`?

**Comment by greghendershott** [comment]
As of commit ad50da3 you may now supply a function to override how `xexprs->scribble-pres` converts any specific HTML element to a scribble part. So:

- "Do what I say": If you have some very specific conversion in mind, now you can get exactly that.

- "Do what I mean": At the same time, if you know some better general default than `<blockquote> => centered`, that most people would prefer most of the time? I'd be happy to update the function to use that as the new default.

    [Although there might be some obvious answer here, I didn't notice it while scanning the Scribble documentation.]

**Comment by shriram** [comment]
Yes, I think there's a very clear correct thing to do! Use `nested` with `#:style 'inset`. 

For instance, this Scribble source
```
This is some

@nested[#:style 'inset]{quoted text}
```
produces
<img width="140" alt="image" src="https://user-images.githubusercontent.com/75030/92995612-f80afa80-f4d2-11ea-84e0-0950f7dc14a1.png">
in HTML and
<img width="75" alt="image" src="https://user-images.githubusercontent.com/75030/92995617-ff320880-f4d2-11ea-8ab4-725b0195aa87.png">
in PDF. 

In the HTML case, this literally turns into a `blockquote`, which is what Markdown (effectively) says it should be:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/75030/92995649-428c7700-f4d3-11ea-851a-7a73c65243de.png">

**Comment by shriram** [comment]
Confirming it works as expected — thanks!

**Comment by greghendershott** [comment]
You're welcome. Thanks for pointing me to the correct Scribble form to use.
